# Generated by Django 5.2.1 on 2025-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FourMChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_m', models.CharField(choices=[('Man', 'Man'), ('Machine/Tool', 'Machine/Tool'), ('Material', 'Material'), ('Method', 'Method')], max_length=20)),
                ('changed_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('change_category', models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned'), ('Abnormal', 'Abnormal')], max_length=20)),
                ('set_up_approval', models.BooleanField()),
                ('retroactive_inspection', models.BooleanField()),
                ('suspected_lot_check', models.BooleanField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
