# Generated by Django 5.2.1 on 2025-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmchange',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
