# Generated by Django 5.2.1 on 2025-08-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fourmchange_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMovementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=100)),
                ('wire_size', models.CharField(blank=True, max_length=50)),
                ('lot_no', models.CharField(blank=True, max_length=50)),
                ('mat_grade', models.CharField(blank=True, max_length=50)),
                ('dept_c', models.CharField(blank=True, max_length=50)),
                ('wp_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMovementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_req', models.CharField(blank=True, max_length=100)),
                ('process_name', models.CharField(blank=True, max_length=100)),
                ('mc_no', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, choices=[('A', 'Morning'), ('B', 'Evening'), ('C', 'Night')], max_length=1)),
                ('change_info', models.CharField(blank=True, max_length=200)),
                ('opr_sign', models.CharField(blank=True, max_length=100)),
                ('qa_sign', models.CharField(blank=True, max_length=100)),
                ('net_wt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app1.materialmovementcard')),
            ],
        ),
    ]
