# Generated by Django 6.0 on 2026-01-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fourmapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcr',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcrs', to='app1.fourmchange'),
        ),
    ]
