# Generated by Django 5.1 on 2026-01-13 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rcr_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of change/incident')),
                ('part_name', models.CharField(help_text='Part Name/Model', max_length=200)),
                ('change_type', models.CharField(help_text='Change Type: Planned/Unplanned/Abnormal', max_length=200)),
                ('suspected_qty', models.PositiveIntegerField(default=0, help_text='Total suspected quantity')),
                ('dispatch_date', models.DateField(blank=True, help_text='Date of dispatch', null=True)),
                ('qty', models.PositiveIntegerField(default=0, help_text='Quantity dispatched/affected')),
                ('city', models.CharField(blank=True, help_text='Customer city', max_length=100)),
                ('invoice', models.CharField(blank=True, help_text='Invoice/Reference number', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Containment remarks or additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rcr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspected_lots', to='app1.rcr')),
            ],
            options={
                'verbose_name': 'Suspected Lot Record',
                'verbose_name_plural': 'Suspected Lot Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
