# Generated by Django 5.2.1 on 2025-08-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_materialmovementcard_materialmovementrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FourMChangeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('nature_of_change', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('part_name_no', models.CharField(blank=True, max_length=100, null=True)),
                ('control_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_no_batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_no_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('retro_qty', models.CharField(blank=True, max_length=50, null=True)),
                ('retro_wh_no', models.CharField(blank=True, max_length=50, null=True)),
                ('retro_assy', models.CharField(blank=True, max_length=50, null=True)),
                ('retro_moog', models.CharField(blank=True, max_length=50, null=True)),
                ('retro_cust', models.CharField(blank=True, max_length=50, null=True)),
                ('retro_ott_pn', models.CharField(blank=True, max_length=50, null=True)),
                ('containment_assy', models.CharField(blank=True, max_length=50, null=True)),
                ('containment_ship', models.CharField(blank=True, max_length=50, null=True)),
                ('containment_lot_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('sl_op', models.CharField(blank=True, max_length=50, null=True)),
                ('sl_production', models.CharField(blank=True, max_length=50, null=True)),
                ('sl_plant_impl', models.CharField(blank=True, max_length=50, null=True)),
                ('material_details_1', models.CharField(blank=True, max_length=100, null=True)),
                ('material_details_2', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FourMTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('noplan', 'No Plan'), ('nochange', 'No Change'), ('change', 'Change')], default='noplan', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='app1.fourmcategory')),
            ],
            options={
                'unique_together': {('category', 'day', 'month')},
            },
        ),
    ]
