# Generated by Django 5.2.10 on 2026-01-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_suspectedlot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('record_no', models.CharField(max_length=100)),
                ('rev_no', models.CharField(max_length=10)),
                ('rev_date', models.DateField()),
                ('record_name', models.TextField()),
                ('retention_period', models.CharField(blank=True, max_length=100)),
                ('disposal_authority', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='format_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('process_owner', models.CharField(max_length=255)),
            ],
        ),
    ]
