# Generated by Django 5.1 on 2025-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_fourmcategory_fourmchangedetail_fourmtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('operator', models.CharField(max_length=100)),
                ('blanking', models.BooleanField(default=False)),
                ('bending', models.BooleanField(default=False)),
                ('punching', models.BooleanField(default=False)),
                ('draw', models.BooleanField(default=False)),
                ('trimming', models.BooleanField(default=False)),
                ('mig_welding', models.BooleanField(default=False)),
                ('tig_welding', models.BooleanField(default=False)),
                ('projection_welding', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
