# Generated by Django 5.1 on 2025-08-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_matrixrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixrow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='matrixrow',
            name='sl_no',
        ),
    ]
