# Generated by Django 5.2.10 on 2026-01-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_formatrecord_processinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('unexpected_change', models.CharField(choices=[('Man', 'Man'), ('Machine', 'Machine'), ('Material', 'Material'), ('Method', 'Method'), ('Others', 'Others')], max_length=20)),
                ('result_confirmation_status', models.CharField(blank=True, max_length=100)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeValidationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('before_change_1', models.CharField(blank=True, max_length=100, null=True)),
                ('before_change_2', models.CharField(blank=True, max_length=100, null=True)),
                ('before_change_3', models.CharField(blank=True, max_length=100, null=True)),
                ('after_change_1', models.CharField(blank=True, max_length=100, null=True)),
                ('after_change_2', models.CharField(blank=True, max_length=100, null=True)),
                ('after_change_3', models.CharField(blank=True, max_length=100, null=True)),
                ('end_change_1', models.CharField(blank=True, max_length=100, null=True)),
                ('end_change_2', models.CharField(blank=True, max_length=100, null=True)),
                ('end_change_3', models.CharField(blank=True, max_length=100, null=True)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app1.changevalidation')),
            ],
        ),
    ]
