# Generated by Django 5.1 on 2025-08-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_matrixrow_options_remove_matrixrow_sl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixrow',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
