# Generated by Django 5.2.10 on 2026-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_changevalidation_changevalidationrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='changevalidation',
            name='change_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
