# Generated by Django 5.2.10 on 2026-01-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_changevalidation_change_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_record_id', models.CharField(max_length=30)),
                ('shopfloor_name', models.CharField(max_length=100)),
                ('line_name', models.CharField(max_length=100)),
                ('station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('process_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pass', 'Pass'), ('fail', 'Fail')], default='in_progress', max_length=20)),
                ('total_production_marks', models.IntegerField(default=0)),
                ('total_quality_marks', models.IntegerField(default=0)),
                ('overall_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_records_created', to=settings.AUTH_USER_MODEL)),
                ('four_m_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_records', to='app1.fourmchange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OJTDailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('plan', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('production_marks', models.IntegerField(default=0)),
                ('rejections', models.IntegerField(blank=True, null=True)),
                ('quality_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ojt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='app1.ojtrecord')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('ojt_record', 'day')},
            },
        ),
    ]
