# Generated by Django 4.2.2 on 2026-01-22 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_changevalidation_change_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationPSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('shopfloor_name', models.CharField(blank=True, max_length=100)),
                ('line_name', models.CharField(blank=True, max_length=100)),
                ('old_batch_no', models.CharField(blank=True, help_text='Last batch before change', max_length=100)),
                ('new_batch_no', models.CharField(help_text='First batch with change', max_length=100)),
                ('psn_start', models.CharField(blank=True, help_text='Starting Serial No.', max_length=100)),
                ('identification_method', models.CharField(help_text='e.g., Green Sticker, Stamp, Tag', max_length=200)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_info', to='app1.fourmchange')),
            ],
        ),
    ]
