# Generated by Django 5.1 on 2025-08-06 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_matrixrow_sequence_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("controlPlanNo", models.CharField(blank=True, max_length=255)),
                ("keyContact", models.CharField(blank=True, max_length=255)),
                ("dateOrig", models.CharField(blank=True, max_length=255)),
                ("dateRev", models.CharField(blank=True, max_length=255)),
                ("prototype", models.BooleanField(default=False)),
                ("prelaunch", models.BooleanField(default=False)),
                ("production", models.BooleanField(default=False)),
                ("coreTeam", models.CharField(blank=True, max_length=255)),
                (
                    "customerEngApprovalDate",
                    models.CharField(blank=True, max_length=255),
                ),
                ("refPartNo", models.CharField(blank=True, max_length=255)),
                (
                    "partNoLatestChangeLevel",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "supplierPlantApprovalDate",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "customerQuantityApprovalDate",
                    models.CharField(blank=True, max_length=255),
                ),
                ("partNameDescription", models.CharField(blank=True, max_length=255)),
                (
                    "otherApprovalDateIfReqd1",
                    models.CharField(blank=True, max_length=255),
                ),
                ("otherApprovalDate1", models.CharField(blank=True, max_length=255)),
                ("supplierPlant", models.CharField(blank=True, max_length=255)),
                (
                    "otherApprovalDateIfReqd2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("otherApprovalDate2", models.CharField(blank=True, max_length=255)),
                ("legend", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("preparedBy", models.CharField(blank=True, max_length=255)),
                ("checkedBy", models.CharField(blank=True, max_length=255)),
                ("approvedBy", models.CharField(blank=True, max_length=255)),
                ("formatNo", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=200)),
                ("part_number", models.CharField(max_length=100)),
                ("customer", models.CharField(max_length=200)),
                ("operation_name", models.CharField(max_length=200)),
                (
                    "overall_judgement",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], default="OK", max_length=2
                    ),
                ),
                ("prepared_by", models.CharField(blank=True, max_length=200)),
                ("approved_by", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255)),
                ("part_number", models.CharField(max_length=255)),
                ("organization_name", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                ("doc_no", models.CharField(blank=True, max_length=255)),
                ("rev_date", models.DateField(blank=True, null=True)),
                ("rev_no", models.CharField(blank=True, max_length=50)),
                ("prepared_by", models.CharField(max_length=255)),
                ("approved_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("part_name_number", models.CharField(max_length=200)),
                ("type_of_change", models.CharField(max_length=200)),
                ("inspected_by", models.CharField(max_length=100)),
                ("lot_qty", models.PositiveIntegerField(default=0)),
                ("ok_qty", models.PositiveIntegerField(default=0)),
                ("reject_qty", models.PositiveIntegerField(default=0)),
                ("rework_qty", models.PositiveIntegerField(default=0)),
                ("parameter", models.CharField(blank=True, max_length=200)),
                ("specification", models.TextField(blank=True)),
                ("inspection_method", models.CharField(blank=True, max_length=200)),
                ("observation1", models.TextField(blank=True)),
                ("observation2", models.TextField(blank=True)),
                ("observation3", models.TextField(blank=True)),
                ("observation4", models.TextField(blank=True)),
                ("observation5", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InProcessParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.CharField(max_length=10)),
                ("parameter_name", models.CharField(max_length=200)),
                ("specification", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=200)),
                ("readings", models.JSONField(blank=True, default=list)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inprocess_parameters",
                        to="app1.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partProcessNo", models.CharField(blank=True, max_length=255)),
                (
                    "processNameOperationDescription",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "machineDeviceJigToolsForMfg",
                    models.CharField(blank=True, max_length=255),
                ),
                ("no", models.CharField(blank=True, max_length=255)),
                (
                    "productCharacteristics",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "processCharacteristics",
                    models.CharField(blank=True, max_length=255),
                ),
                ("specialCharClass", models.CharField(blank=True, max_length=255)),
                ("productProcessSpec", models.CharField(blank=True, max_length=255)),
                ("toleranceControlSpec", models.CharField(blank=True, max_length=255)),
                (
                    "evaluationMeasurementTechnique",
                    models.CharField(blank=True, max_length=255),
                ),
                ("sampleSize", models.CharField(blank=True, max_length=255)),
                ("sampleFreq", models.CharField(blank=True, max_length=255)),
                ("periodicalResp", models.CharField(blank=True, max_length=255)),
                ("primaryResp", models.CharField(blank=True, max_length=255)),
                ("controlMethod", models.CharField(blank=True, max_length=255)),
                ("record", models.CharField(blank=True, max_length=255)),
                ("reactionPlan", models.CharField(blank=True, max_length=255)),
                (
                    "control_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="app1.controlplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_no", models.PositiveIntegerField()),
                ("process_no", models.CharField(blank=True, max_length=100)),
                ("move", models.CharField(blank=True, max_length=100)),
                ("store", models.CharField(blank=True, max_length=100)),
                ("operation", models.CharField(blank=True, max_length=100)),
                ("delay", models.CharField(blank=True, max_length=100)),
                ("process_description", models.TextField(blank=True)),
                ("product_characteristics", models.TextField(blank=True)),
                ("process_characteristics", models.TextField(blank=True)),
                (
                    "process_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="app1.processflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.CharField(max_length=10)),
                ("parameter_name", models.CharField(max_length=200)),
                ("specification", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=200)),
                ("process_machine_no", models.CharField(blank=True, max_length=100)),
                ("process_operator", models.CharField(blank=True, max_length=100)),
                ("process_date_time", models.CharField(blank=True, max_length=100)),
                ("change_machine_no", models.CharField(blank=True, max_length=100)),
                ("change_operator", models.CharField(blank=True, max_length=100)),
                ("change_date_time", models.CharField(blank=True, max_length=100)),
                ("lqa_machine_no", models.CharField(blank=True, max_length=100)),
                ("lqa_operator", models.CharField(blank=True, max_length=100)),
                ("lqa_date_time", models.CharField(blank=True, max_length=100)),
                ("action", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_parameters",
                        to="app1.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("change_description", models.TextField(blank=True)),
                ("approved_by_supplier", models.CharField(blank=True, max_length=255)),
                ("approved_by_customer", models.CharField(blank=True, max_length=255)),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("operation", "Operation"),
                            ("transportation", "Transportation"),
                            ("inspection", "Inspection"),
                            ("operationInspection", "Operation + Inspection"),
                            ("delay", "Delay"),
                            ("storage", "Storage"),
                            ("", "None"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "process_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="app1.processflow",
                    ),
                ),
            ],
        ),
    ]
