# Generated by Django 5.1 on 2025-08-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_controlplan_inspectionreport_processflow_rcr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionreport",
            name="status",
        ),
    ]
