# Generated by Django 4.2.2 on 2026-01-22 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_identificationpsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationpsn',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
