# Generated by Django 5.1 on 2025-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_remove_inspectionreport_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={"ordering": ["s_no"]},
        ),
        migrations.AddField(
            model_name="processflow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="processflow",
            name="approved_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="processflow",
            name="prepared_by",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
