# Generated by Django 5.1 on 2025-10-21 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_alter_process_options_processflow_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FourMAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_taken", models.TextField()),
                ("set_up_approval", models.BooleanField(default=False)),
                ("retroactive_inspection", models.BooleanField(default=False)),
                ("suspected_lot_check", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FourMCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Unplanned", "Unplanned"),
                            ("Abnormal", "Abnormal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Definition")),
            ],
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shopfloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="action_taken",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="change_category",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="changed_description",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="retroactive_inspection",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="set_up_approval",
        ),
        migrations.RemoveField(
            model_name="fourmchange",
            name="suspected_lot_check",
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="record_id",
            field=models.CharField(
                default="TEMP-000", editable=False, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fourmchange",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.fourmaction",
            ),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="app1.fourmcategories",
            ),
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.fourmcategories",
            ),
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.line",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="shopfloor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="app1.shopfloor",
            ),
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="shopfloor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.shopfloor",
            ),
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="app1.line",
                    ),
                ),
            ],
            options={
                "unique_together": {("line", "name")},
            },
        ),
        migrations.AddField(
            model_name="fourmchange",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.station",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("shopfloor", "name")},
        ),
    ]
