# Generated by Django 5.2.10 on 2026-01-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_identificationpsn_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='containment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('process', models.CharField(blank=True, max_length=100)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('change_type', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('potential_risk', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('containment_action', models.TextField(blank=True)),
                ('area_affected', models.TextField(blank=True)),
                ('duration', models.TextField(blank=True)),
                ('responsibility', models.TextField(blank=True)),
                ('inspection_method', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('trial_quantity', models.CharField(blank=True, max_length=100)),
                ('defects_observed', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sheet', to='app1.fourmchange')),
            ],
            options={
                'verbose_name': '4M Change Detail',
                'verbose_name_plural': '4M Change Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
