# Generated by Django 4.2.2 on 2026-01-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_containment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmchangedetail',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_details', to='app1.fourmchange'),
        ),
    ]
