# Generated by Django 5.1 on 2025-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_fourmaction_fourmcategories_line_shopfloor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fourmaction",
            name="approving_authority",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="change_record",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="containment_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="customer_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="identification_psn_batch_no",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fourmaction",
            name="ojt",
            field=models.BooleanField(default=False),
        ),
    ]
