# Generated by Django 4.2.2 on 2026-01-23 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fourmchangedetail_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfloor',
            name='sheet_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Characteristics (Assembly)'), ('PROCESS', 'Process Check (Oven/Molding)'), ('PAINT', 'Paint Quality Sheet'), ('TOOLING', 'Perishable Tooling Sheet')], default='PRODUCT', help_text='Which Setup Verification sheet should be used for this shopfloor?', max_length=20),
        ),
        migrations.CreateModel(
            name='SetupSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_type', models.CharField(max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('overall_result', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG')], default='OK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_sheet', to='app1.fourmchange')),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('change', 'sheet_type')},
            },
        ),
    ]
