# Generated by Django 6.0 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fourmaction_approving_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmcategories',
            name='four_m',
            field=models.CharField(choices=[('Man', 'Man'), ('Machine/Tool', 'Machine/Tool'), ('Material', 'Material'), ('Method', 'Method')], default='man', max_length=20),
            preserve_default=False,
        ),
    ]
