# Generated by Django 5.1 on 2026-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fourmaction_approving_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmchange',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], default='A', max_length=1),
        ),
    ]
