# Generated by Django 4.2.2 on 2026-01-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_shopfloor_sheet_type_setupsheetentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApprovalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('reason_for_fpp', models.CharField(blank=True, max_length=50)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=150)),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('modification_details', models.TextField(blank=True)),
                ('prepared_by_sign', models.CharField(blank=True, max_length=100)),
                ('approved_by_sign', models.CharField(blank=True, max_length=100)),
                ('inspection_data', models.JSONField(blank=True, default=dict)),
                ('comments_data', models.JSONField(blank=True, default=list)),
                ('insp_date', models.DateField(blank=True, null=True)),
                ('feeding_date', models.DateField(blank=True, null=True)),
                ('feeding_time', models.TimeField(blank=True, null=True)),
                ('person_incharge', models.CharField(blank=True, max_length=100)),
                ('sec_mgr', models.CharField(blank=True, max_length=100)),
                ('person_incharge_prod', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_approval_sheet_data', to='app1.fourmchange')),
            ],
        ),
    ]
