# Generated by Django 5.1 on 2026-01-06 09:14

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('app1', '0013_fourmchange_shift'),
#     ]

#     operations = [
#         migrations.AlterUniqueTogether(
#             name='fourmchangedetail',
#             unique_together={('date', 'time', 'shift', 'record_id')},
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='action_taken_on_ng_parts',
#             field=models.CharField(blank=True, max_length=200, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='applicability_containment',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='applicability_retro',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='applicability_setup',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='category_type',
#             field=models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned'), ('Abnormal', 'Abnormal')], max_length=20, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='containmentcheck_ng_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='containmentcheck_ok_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='containmentcheck_total_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='customer_approval_required',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='informed_maintenance',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='informed_others',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='informed_production',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='informed_quality',
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='line',
#             field=models.CharField(blank=True, max_length=100, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='model',
#             field=models.CharField(blank=True, max_length=100, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='production_approval',
#             field=models.CharField(blank=True, max_length=100, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='quality_approval',
#             field=models.CharField(blank=True, max_length=100, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='record_id',
#             field=models.CharField(blank=True, max_length=30, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='retrocheck_ng_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='retrocheck_ok_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='retrocheck_total_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='setup_ng_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='setup_ok_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='setup_total_qty',
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='shift',
#             field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], default='A', max_length=1),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='station',
#             field=models.CharField(blank=True, max_length=100, null=True),
#         ),
#         migrations.AddField(
#             model_name='fourmchangedetail',
#             name='traceability',
#             field=models.CharField(blank=True, max_length=200, null=True),
#         ),
#         migrations.AlterField(
#             model_name='fourmchangedetail',
#             name='nature_of_change',
#             field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Machine', 'Machine'), ('Material', 'Material'), ('Method', 'Method')], max_length=20, null=True),
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='containment_assy',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='containment_lot_invoice',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='containment_ship',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='control_no',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='lot_no_batch_no',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='material_details_1',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='material_details_2',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='mc_no',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='part_name_no',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='remarks',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_assy',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_cust',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_moog',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_ott_pn',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_qty',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='retro_wh_no',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='sl_op',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='sl_plant_impl',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='sl_production',
#         ),
#         migrations.RemoveField(
#             model_name='fourmchangedetail',
#             name='tracking_no_serial',
#         ),
#     ]

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_fourmchange_shift'),
    ]

    operations = [
        # FIRST: Add all new fields (including 'shift')
        migrations.AddField(
            model_name='fourmchangedetail',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='record_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='action_taken_on_ng_parts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='applicability_containment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='applicability_retro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='applicability_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned'), ('Abnormal', 'Abnormal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='containmentcheck_ng_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='containmentcheck_ok_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='containmentcheck_total_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='customer_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='informed_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='informed_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='informed_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='informed_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='production_approval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='quality_approval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='retrocheck_ng_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='retrocheck_ok_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='retrocheck_total_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='setup_ng_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='setup_ok_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='setup_total_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangedetail',
            name='traceability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        
        # SECOND: Alter existing fields
        migrations.AlterField(
            model_name='fourmchangedetail',
            name='nature_of_change',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Machine', 'Machine'), ('Material', 'Material'), ('Method', 'Method')], max_length=20, null=True),
        ),
        
        # THIRD: Remove old fields
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='containment_assy',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='containment_lot_invoice',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='containment_ship',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='control_no',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='lot_no_batch_no',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='material_details_1',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='material_details_2',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='mc_no',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='part_name_no',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_assy',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_cust',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_moog',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_ott_pn',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_qty',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='retro_wh_no',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='sl_op',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='sl_plant_impl',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='sl_production',
        ),
        migrations.RemoveField(
            model_name='fourmchangedetail',
            name='tracking_no_serial',
        ),
        
        # LAST: Add the unique_together constraint (after 'shift' field exists)
        migrations.AlterUniqueTogether(
            name='fourmchangedetail',
            unique_together={('date', 'time', 'shift', 'record_id')},
        ),
    ]