# Generated by Django 5.2.10 on 2026-01-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_customerapprovalsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel_photos/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(choices=[('Engineer', 'Engineer'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Technician', 'Technician')], default='Supervisor', max_length=30)),
                ('responsibilities', models.TextField(blank=True, help_text='Write main responsibilities (one per line is good)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopfloor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='app1.shopfloor')),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'ordering': ['shopfloor', 'name'],
            },
        ),
    ]
