# Generated by Django 5.2.10 on 2026-01-27 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('operator_signature', models.CharField(max_length=100)),
                ('supervisor_signature', models.CharField(max_length=100)),
                ('overall_result', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=4, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('four_m_change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_check_sheet', to='app1.fourmchange')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCheckPointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG'), ('NA', 'NA')], max_length=2)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='app1.machinechecksheet')),
            ],
            options={
                'unique_together': {('sheet', 'check_point_no')},
            },
        ),
    ]
