# Generated by Django 5.1 on 2026-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_fourmchangedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourmchangedetail',
            name='nature_of_change',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Machine/Tool', 'Machine/Tool'), ('Material', 'Material'), ('Method', 'Method')], max_length=20, null=True),
        ),
    ]
