# Generated by Django 5.2.10 on 2026-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_machinechecksheet_machinecheckpointstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmaction',
            name='in_process_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fourmaction',
            name='machine_check_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
