# Generated by Django 5.2.10 on 2026-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_fourmaction_in_process_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourmchange',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], default='A', max_length=1),
        ),
    ]
