# Generated by Django 5.2.10 on 2026-01-28 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_fourmchange_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Report ID')),
                ('product', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=50)),
                ('customer', models.CharField(blank=True, default='', max_length=100)),
                ('shift', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.DateField()),
                ('unexpected_change', models.CharField(choices=[('Man', 'Man'), ('Machine', 'Machine'), ('Material', 'Material'), ('Method', 'Method'), ('Others', 'Others')], max_length=20)),
                ('change_point', models.TextField(blank=True, default='')),
                ('result_confirmation_status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('prepared_by', models.CharField(blank=True, default='', max_length=100)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validation Report',
                'verbose_name_plural': 'Validation Reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=250)),
                ('before_change_1', models.CharField(blank=True, default='', max_length=100)),
                ('before_change_2', models.CharField(blank=True, default='', max_length=100)),
                ('before_change_3', models.CharField(blank=True, default='', max_length=100)),
                ('after_change_1', models.CharField(blank=True, default='', max_length=100)),
                ('after_change_2', models.CharField(blank=True, default='', max_length=100)),
                ('after_change_3', models.CharField(blank=True, default='', max_length=100)),
                ('end_change_1', models.CharField(blank=True, default='', max_length=100)),
                ('end_change_2', models.CharField(blank=True, default='', max_length=100)),
                ('end_change_3', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app1.validationreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
