# Generated by Django 5.2.10 on 2026-01-28 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_validationreport_validationrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(help_text='e.g. 10476, 10519', max_length=10, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('current_line', models.CharField(blank=True, max_length=100)),
                ('current_station', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField()),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter valid phone number')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-date_of_joining', 'emp_id'],
            },
        ),
    ]
