import { Employee } from "./MasterTable";

export const DUMMY_EMPLOYEES: Employee[] = [
    {
        emp_id: "EMP001",
        first_name: "John",
        last_name: "Doe",
        date_of_joining: "2023-01-15",
        birth_date: "1990-05-20",
        sex: "M",
        email: "john.doe@example.com",
        phone: "9876543210",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 1, station_name: "Station 1" },
        photo: null
    },
    {
        emp_id: "EMP002",
        first_name: "Jane",
        last_name: "Smith",
        date_of_joining: "2023-02-10",
        birth_date: "1992-08-15",
        sex: "F",
        email: "jane.smith@example.com",
        phone: "9876543211",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 2, station_name: "Station 2" },
        photo: null
    },
    {
        emp_id: "EMP003",
        first_name: "Robert",
        last_name: "Brown",
        date_of_joining: "2023-03-05",
        birth_date: "1988-12-10",
        sex: "M",
        email: "robert.brown@example.com",
        phone: "9876543212",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 2, line_name: "Inspection Line 1" },
        current_station: { station_id: 5, station_name: "Final QC" },
        photo: null
    },
    {
        emp_id: "EMP004",
        first_name: "Emily",
        last_name: "Davis",
        date_of_joining: "2023-04-12",
        birth_date: "1995-03-25",
        sex: "F",
        email: "emily.davis@example.com",
        phone: "9876543213",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 3, station_name: "Station 3" },
        photo: null
    },
    {
        emp_id: "EMP005",
        first_name: "Michael",
        last_name: "Wilson",
        date_of_joining: "2023-05-20",
        birth_date: "1991-07-30",
        sex: "M",
        email: "michael.wilson@example.com",
        phone: "9876543214",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 3, line_name: "Dispatch Line" },
        current_station: { station_id: 8, station_name: "Packing" },
        photo: null
    },
    {
        emp_id: "EMP006",
        first_name: "Sarah",
        last_name: "Miller",
        date_of_joining: "2023-06-18",
        birth_date: "1993-11-12",
        sex: "F",
        email: "sarah.miller@example.com",
        phone: "9876543215",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP007",
        first_name: "David",
        last_name: "Garcia",
        date_of_joining: "2023-07-22",
        birth_date: "1989-02-14",
        sex: "M",
        email: "david.garcia@example.com",
        phone: "9876543216",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 2, line_name: "Inspection Line 1" },
        current_station: { station_id: 6, station_name: "Initial QC" },
        photo: null
    },
    {
        emp_id: "EMP008",
        first_name: "Linda",
        last_name: "Martinez",
        date_of_joining: "2023-08-30",
        birth_date: "1994-09-05",
        sex: "F",
        email: "linda.martinez@example.com",
        phone: "9876543217",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line B" },
        current_station: { station_id: 11, station_name: "Station B2" },
        photo: null
    },
    {
        emp_id: "EMP009",
        first_name: "James",
        last_name: "Anderson",
        date_of_joining: "2023-09-15",
        birth_date: "1987-04-22",
        sex: "M",
        email: "james.anderson@example.com",
        phone: "9876543218",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 3, line_name: "Inventory Line" },
        current_station: { station_id: 9, station_name: "Sorting" },
        photo: null
    },
    {
        emp_id: "EMP010",
        first_name: "Barbara",
        last_name: "Thomas",
        date_of_joining: "2023-10-05",
        birth_date: "1996-01-18",
        sex: "F",
        email: "barbara.thomas@example.com",
        phone: "9876543219",
        department: { department_id: 4, department_name: "Maintenance" },
        current_line: { line_id: 4, line_name: "Facility" },
        current_station: { station_id: 15, station_name: "Workshop" },
        photo: null
    }
];
