import { Employee } from "./MasterTable";

export const DUMMY_EMPLOYEES: Employee[] = [
    {
        emp_id: "EMP001",
        first_name: "John",
        last_name: "Doe",
        date_of_joining: "2023-01-15",
        birth_date: "1990-05-20",
        sex: "M",
        email: "john.doe@example.com",
        phone: "9876543210",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 1, station_name: "Station 1" },
        photo: null
    },
    {
        emp_id: "EMP002",
        first_name: "Jane",
        last_name: "Smith",
        date_of_joining: "2023-02-10",
        birth_date: "1992-08-15",
        sex: "F",
        email: "jane.smith@example.com",
        phone: "9876543211",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 2, station_name: "Station 2" },
        photo: null
    },
    {
        emp_id: "EMP003",
        first_name: "Robert",
        last_name: "Brown",
        date_of_joining: "2023-03-05",
        birth_date: "1988-12-10",
        sex: "M",
        email: "robert.brown@example.com",
        phone: "9876543212",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 2, line_name: "Inspection Line 1" },
        current_station: { station_id: 5, station_name: "Final QC" },
        photo: null
    },
    {
        emp_id: "EMP004",
        first_name: "Emily",
        last_name: "Davis",
        date_of_joining: "2023-04-12",
        birth_date: "1995-03-25",
        sex: "F",
        email: "emily.davis@example.com",
        phone: "9876543213",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 3, station_name: "Station 3" },
        photo: null
    },
    {
        emp_id: "EMP005",
        first_name: "Michael",
        last_name: "Wilson",
        date_of_joining: "2023-05-20",
        birth_date: "1991-07-30",
        sex: "M",
        email: "michael.wilson@example.com",
        phone: "9876543214",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 3, line_name: "Dispatch Line" },
        current_station: { station_id: 8, station_name: "Packing" },
        photo: null
    },
    {
        emp_id: "EMP006",
        first_name: "Sarah",
        last_name: "Miller",
        date_of_joining: "2023-06-18",
        birth_date: "1993-11-12",
        sex: "F",
        email: "sarah.miller@example.com",
        phone: "9876543215",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP007",
        first_name: "David",
        last_name: "Garcia",
        date_of_joining: "2023-07-22",
        birth_date: "1989-02-14",
        sex: "M",
        email: "david.garcia@example.com",
        phone: "9876543216",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 2, line_name: "Inspection Line 1" },
        current_station: { station_id: 6, station_name: "Initial QC" },
        photo: null
    },
    {
        emp_id: "EMP008",
        first_name: "Linda",
        last_name: "Martinez",
        date_of_joining: "2023-08-30",
        birth_date: "1994-09-05",
        sex: "F",
        email: "linda.martinez@example.com",
        phone: "9876543217",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line B" },
        current_station: { station_id: 11, station_name: "Station B2" },
        photo: null
    },
    {
        emp_id: "EMP009",
        first_name: "James",
        last_name: "Anderson",
        date_of_joining: "2023-09-15",
        birth_date: "1987-04-22",
        sex: "M",
        email: "james.anderson@example.com",
        phone: "9876543218",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 3, line_name: "Inventory Line" },
        current_station: { station_id: 9, station_name: "Sorting" },
        photo: null
    },
    {
        emp_id: "EMP010",
        first_name: "Barbara",
        last_name: "Thomas",
        date_of_joining: "2023-10-05",
        birth_date: "1996-01-18",
        sex: "F",
        email: "barbara.thomas@example.com",
        phone: "9876543219",
        department: { department_id: 4, department_name: "Maintenance" },
        current_line: { line_id: 4, line_name: "Facility" },
        current_station: { station_id: 15, station_name: "Workshop" },
        photo: null
    },
    {
        emp_id: "EMP011",
        first_name: "Mark",
        last_name: "Robinson",
        date_of_joining: "2023-11-12",
        birth_date: "1985-06-25",
        sex: "M",
        email: "mark.robinson@example.com",
        phone: "9876543220",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 1, station_name: "Station 1" },
        photo: null
    },
    {
        emp_id: "EMP012",
        first_name: "Patricia",
        last_name: "White",
        date_of_joining: "2023-12-01",
        birth_date: "1997-09-14",
        sex: "F",
        email: "patricia.white@example.com",
        phone: "9876543221",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 2, line_name: "Inspection Line 1" },
        current_station: { station_id: 5, station_name: "Final QC" },
        photo: null
    },
    {
        emp_id: "EMP013",
        first_name: "Steven",
        last_name: "Hall",
        date_of_joining: "2024-01-10",
        birth_date: "1986-11-30",
        sex: "M",
        email: "steven.hall@example.com",
        phone: "9876543222",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP014",
        first_name: "Jennifer",
        last_name: "Lewis",
        date_of_joining: "2024-02-15",
        birth_date: "1994-04-12",
        sex: "F",
        email: "jennifer.lewis@example.com",
        phone: "9876543223",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 3, line_name: "Dispatch Line" },
        current_station: { station_id: 8, station_name: "Packing" },
        photo: null
    },
    {
        emp_id: "EMP015",
        first_name: "Charles",
        last_name: "Young",
        date_of_joining: "2024-03-01",
        birth_date: "1990-10-22",
        sex: "M",
        email: "charles.young@example.com",
        phone: "9876543224",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 2, station_name: "Station 2" },
        photo: null
    },
    {
        emp_id: "EMP016",
        first_name: "Thomas",
        last_name: "Wright",
        date_of_joining: "2024-03-15",
        birth_date: "1992-04-10",
        sex: "M",
        email: "thomas.wright@example.com",
        phone: "9876543225",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP017",
        first_name: "Jessica",
        last_name: "López",
        date_of_joining: "2024-04-01",
        birth_date: "1995-07-20",
        sex: "F",
        email: "jessica.lopez@example.com",
        phone: "9876543226",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 5, line_name: "Inspection Line 2" },
        current_station: { station_id: 20, station_name: "Visual Check" },
        photo: null
    },
    {
        emp_id: "EMP018",
        first_name: "Ryan",
        last_name: "King",
        date_of_joining: "2024-04-15",
        birth_date: "1988-11-30",
        sex: "M",
        email: "ryan.king@example.com",
        phone: "9876543227",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 3, station_name: "Station 3" },
        photo: null
    },
    {
        emp_id: "EMP019",
        first_name: "Angela",
        last_name: "Scott",
        date_of_joining: "2024-05-01",
        birth_date: "1991-02-14",
        sex: "F",
        email: "angela.scott@example.com",
        phone: "9876543228",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 8, line_name: "Dispatch Line" },
        current_station: { station_id: 30, station_name: "Loading" },
        photo: null
    },
    {
        emp_id: "EMP020",
        first_name: "Kevin",
        last_name: "Green",
        date_of_joining: "2024-05-15",
        birth_date: "1993-09-05",
        sex: "M",
        email: "kevin.green@example.com",
        phone: "9876543229",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 11, station_name: "Station B2" },
        photo: null
    },
    {
        emp_id: "EMP021",
        first_name: "Laura",
        last_name: "Adams",
        date_of_joining: "2024-06-01",
        birth_date: "1994-12-10",
        sex: "F",
        email: "laura.adams@example.com",
        phone: "9876543230",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 10, line_name: "Paint Line" },
        current_station: { station_id: 40, station_name: "Coating" },
        photo: null
    },
    {
        emp_id: "EMP022",
        first_name: "Matthew",
        last_name: "Baker",
        date_of_joining: "2024-06-15",
        birth_date: "1987-03-25",
        sex: "M",
        email: "matthew.baker@example.com",
        phone: "9876543231",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 1, station_name: "Station 1" },
        photo: null
    },
    {
        emp_id: "EMP023",
        first_name: "Amy",
        last_name: "Gonzalez",
        date_of_joining: "2024-07-01",
        birth_date: "1996-06-18",
        sex: "F",
        email: "amy.gonzalez@example.com",
        phone: "9876543232",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 5, line_name: "Inspection Line 2" },
        current_station: { station_id: 21, station_name: "Dimensional Audit" },
        photo: null
    },
    {
        emp_id: "EMP024",
        first_name: "Brian",
        last_name: "Nelson",
        date_of_joining: "2024-07-15",
        birth_date: "1989-10-12",
        sex: "M",
        email: "brian.nelson@example.com",
        phone: "9876543233",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 12, station_name: "Station B3" },
        photo: null
    },
    {
        emp_id: "EMP025",
        first_name: "Lisa",
        last_name: "Carter",
        date_of_joining: "2024-08-01",
        birth_date: "1992-01-22",
        sex: "F",
        email: "lisa.carter@example.com",
        phone: "9876543234",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 9, line_name: "Warehouse Line" },
        current_station: { station_id: 35, station_name: "Inventory" },
        photo: null
    },
    {
        emp_id: "EMP026",
        first_name: "Gary",
        last_name: "Mitchell",
        date_of_joining: "2024-08-15",
        birth_date: "1985-05-14",
        sex: "M",
        email: "gary.mitchell@example.com",
        phone: "9876543235",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 4, station_name: "Station 4" },
        photo: null
    },
    {
        emp_id: "EMP027",
        first_name: "Michelle",
        last_name: "Perez",
        date_of_joining: "2024-09-01",
        birth_date: "1997-08-30",
        sex: "F",
        email: "michelle.perez@example.com",
        phone: "9876543236",
        department: { department_id: 4, department_name: "Maintenance" },
        current_line: { line_id: 11, line_name: "Utility Group" },
        current_station: { station_id: 50, station_name: "Electrical" },
        photo: null
    },
    {
        emp_id: "EMP028",
        first_name: "Jason",
        last_name: "Roberts",
        date_of_joining: "2024-09-15",
        birth_date: "1990-11-12",
        sex: "M",
        email: "jason.roberts@example.com",
        phone: "9876543237",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP029",
        first_name: "Kimberly",
        last_name: "Turner",
        date_of_joining: "2024-10-01",
        birth_date: "1987-02-18",
        sex: "F",
        email: "kimberly.turner@example.com",
        phone: "9876543238",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 5, line_name: "Inspection Line 2" },
        current_station: { station_id: 22, station_name: "Lab Testing" },
        photo: null
    },
    {
        emp_id: "EMP030",
        first_name: "Jeffrey",
        last_name: "Phillips",
        date_of_joining: "2024-10-15",
        birth_date: "1994-06-25",
        sex: "M",
        email: "jeffrey.phillips@example.com",
        phone: "9876543239",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 2, station_name: "Station 2" },
        photo: null
    },
    {
        emp_id: "EMP031",
        first_name: "Deborah",
        last_name: "Campbell",
        date_of_joining: "2024-11-01",
        birth_date: "1986-09-14",
        sex: "F",
        email: "deborah.campbell@example.com",
        phone: "9876543240",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 8, line_name: "Dispatch Line" },
        current_station: { station_id: 31, station_name: "Shipping" },
        photo: null
    },
    {
        emp_id: "EMP032",
        first_name: "George",
        last_name: "Parker",
        date_of_joining: "2024-11-15",
        birth_date: "1994-03-30",
        sex: "M",
        email: "george.parker@example.com",
        phone: "9876543241",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 11, station_name: "Station B2" },
        photo: null
    },
    {
        emp_id: "EMP033",
        first_name: "Nancy",
        last_name: "Evans",
        date_of_joining: "2024-12-01",
        birth_date: "1991-10-12",
        sex: "F",
        email: "nancy.evans@example.com",
        phone: "9876543242",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 10, line_name: "Paint Line" },
        current_station: { station_id: 41, station_name: "Spraying" },
        photo: null
    },
    {
        emp_id: "EMP034",
        first_name: "Paul",
        last_name: "Edwards",
        date_of_joining: "2024-12-15",
        birth_date: "1989-05-22",
        sex: "M",
        email: "paul.edwards@example.com",
        phone: "9876543243",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 3, station_name: "Station 3" },
        photo: null
    },
    {
        emp_id: "EMP035",
        first_name: "Karen",
        last_name: "Collins",
        date_of_joining: "2025-01-01",
        birth_date: "1996-12-05",
        sex: "F",
        email: "karen.collins@example.com",
        phone: "9876543244",
        department: { department_id: 2, department_name: "Quality" },
        current_line: { line_id: 5, line_name: "Inspection Line 2" },
        current_station: { station_id: 20, station_name: "Visual Check" },
        photo: null
    },
    {
        emp_id: "EMP036",
        first_name: "Donald",
        last_name: "Stewart",
        date_of_joining: "2025-01-15",
        birth_date: "1985-04-18",
        sex: "M",
        email: "donald.stewart@example.com",
        phone: "9876543245",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 12, station_name: "Station B3" },
        photo: null
    },
    {
        emp_id: "EMP037",
        first_name: "Betty",
        last_name: "Morris",
        date_of_joining: "2025-02-01",
        birth_date: "1993-02-25",
        sex: "F",
        email: "betty.morris@example.com",
        phone: "9876543246",
        department: { department_id: 3, department_name: "Logistics" },
        current_line: { line_id: 9, line_name: "Warehouse Line" },
        current_station: { station_id: 36, station_name: "Receiving" },
        photo: null
    },
    {
        emp_id: "EMP038",
        first_name: "Kenneth",
        last_name: "Rogers",
        date_of_joining: "2025-02-15",
        birth_date: "1994-08-30",
        sex: "M",
        email: "kenneth.rogers@example.com",
        phone: "9876543247",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 1, line_name: "Assembly Line A" },
        current_station: { station_id: 4, station_name: "Station 4" },
        photo: null
    },
    {
        emp_id: "EMP039",
        first_name: "Cynthia",
        last_name: "Reed",
        date_of_joining: "2025-03-01",
        birth_date: "1987-11-12",
        sex: "F",
        email: "cynthia.reed@example.com",
        phone: "9876543248",
        department: { department_id: 1, department_name: "Production" },
        current_line: { line_id: 2, line_name: "Assembly Line B" },
        current_station: { station_id: 10, station_name: "Station B1" },
        photo: null
    },
    {
        emp_id: "EMP040",
        first_name: "Bobby",
        last_name: "Cook",
        date_of_joining: "2025-03-15",
        birth_date: "1995-01-18",
        sex: "M",
        email: "bobby.cook@example.com",
        phone: "9876543249",
        department: { department_id: 4, department_name: "Maintenance" },
        current_line: { line_id: 11, line_name: "Utility Group" },
        current_station: { station_id: 51, station_name: "Mechanical" },
        photo: null
    }
];
